# Generated by Django 4.2.7 on 2023-11-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_alter_staff_categories_alter_staff_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('constracting_party', models.CharField(default=None, max_length=50, null=True)),
                ('work_in_progress', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateField(blank=True, default='1300-01-01', null=True)),
                ('delay', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('category', models.ManyToManyField(default=None, null=True, related_name='Project', to='home.category')),
                ('staff', models.ManyToManyField(default=None, null=True, related_name='Project', to='home.staff')),
            ],
        ),
    ]
