# Generated by Django 4.2.7 on 2023-11-19 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('contracting_party', models.CharField(max_length=50)),
                ('started', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('Work_in_progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Delay', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('categories', models.ManyToManyField(related_name='project', to='home.category')),
                ('staffs', models.ManyToManyField(related_name='project', to='home.staff')),
            ],
        ),
    ]
