# Generated by Django 4.2.7 on 2023-11-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_staff_category_staffs'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime', models.IntegerField()),
                ('FinancialReward', models.DecimalField(decimal_places=3, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=20)),
                ('salary', models.DecimalField(decimal_places=3, max_digits=20)),
                ('staffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='home.staff')),
            ],
        ),
    ]
