# Generated by Django 4.2.7 on 2023-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_staff_categories_alter_staff_experience_and_more'),
        ('activity', '0002_alter_project_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(default=None, related_name='Project', to='home.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='staff',
            field=models.ManyToManyField(default=None, related_name='Project', to='home.staff'),
        ),
    ]
