# Generated by Django 4.2.7 on 2023-11-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_payslip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaySlip',
        ),
    ]
