# Generated by Django 4.2.7 on 2023-11-19 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('employe_rewards', models.CharField(choices=[('To', 'Time off'), ('G', 'Gifts'), ('WH', 'Work from home days'), ('Gc', 'Gift cards'), ('C', 'Certificates')], default='None', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('expert', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('contracting_party', models.CharField(max_length=50)),
                ('started', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('Work_in_progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Delay', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('categories', models.ManyToManyField(related_name='project', to='home.category')),
                ('staffs', models.ManyToManyField(related_name='project', to='home.staff')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.staff'),
        ),
    ]
