# Generated by Django 4.2.7 on 2023-11-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='staff',
            new_name='staffs',
        ),
    ]
