# Generated by Django 4.2.7 on 2023-11-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_staff_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='categories',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='home.category'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='expert',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lastname',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
